[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "6pkPqwhQhgm8m8rAYAeTGrdVLyQHubYjb8Kfpcg2biZa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
